server:
  port: 8083

spring:
  application:
    name: registration-service
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Ho@ng1911
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

services:
  course-service:
    base-url: http://localhost:8082

# THÊM ĐOẠN NÀY VÀO:
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
